version: '3.8'

services:
  app:
    build:
      context: .
      target: production-stage
    container_name: client-manager-app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx

networks:
  app-network:
    driver: bridge

volumes:
  logs: 