version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/clientdb
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clientdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 